### ISSUE TITLE
`WaitPub` may wait more than necessary

### ISSUE THREAD

**Issue by schomatis** [ipfs/go-mfs#38]
(I may not be completely following the `Republisher` logic here.) `WaitPub` sends a channel to a channel for `Run` to take it and signal through it that the `publish` has been issued,

https://github.com/ipfs/go-mfs/blob/2c1b835ceb3a181336651f2285dc4a13b9266c32/system.go#L258-L260

but the channel `pubnowch` through which the "inner" `pubnowresp` channel is being sent is processed in parallel with the `publish` timers,

https://github.com/ipfs/go-mfs/blob/2c1b835ceb3a181336651f2285dc4a13b9266c32/system.go#L299-L307

with the intention (I'm assuming) that it will trigger an instantaneous `publish` without waiting for the timeouts (since someone is waiting for it).

Through this signaling mechanism there is the non-negligible chance (I think) that any of the timers will be processed instead of the `pubnowch` channel which would mean that the publish will indeed happen but the user will keep waiting an indefinite amount of time until another value is sent to the `Republisher`.

**Comment by Stebalien** [comment]
Yep, that looks like a bug. Really, the bug starts in `WaitPub` when we release the lock. Once we release that lock, the value can be published at any time.

**Comment by schomatis** [comment]
I think the easiest solution at the moment would be to remove `WaitPub` and use instead an exported version of the `publish` method, as we seem to be using `WaitPub` just to trigger a publish of *any* value (since there is a gap between the `Update` and `WaitPub` calls and the user just cares that the updated value or any superseding version was published).

This would entail adding a couple of checks in `publish` to detect if the `Republisher` has been closed and maybe also protecting the user-supplied `PubFunc` function (which I'm not sure if it's supposed to be thread-safe) but I think it would help to simplify the entire `Republisher` logic.

It would also help alleviate the concurrent `WaitPub` and `Update` issue where two (or more) users can update a value and wait for the publish simultaneously with the second value overriding the first which would cause only a single `publish` and it would leave a user locked in `WaitPub` (needing a new independent `Update` to unlock it).

@Stebalien WDYT?

**Comment by schomatis** [comment]
(The changes would also take care of https://github.com/ipfs/go-mfs/issues/35.)

**Comment by Stebalien** [comment]
> I think the easiest solution at the moment would be to remove WaitPub and use instead an exported version of the publish method, as we seem to be using WaitPub just to trigger a publish of any value (since there is a gap between the Update and WaitPub calls and the user just cares that the updated value or any superseding version was published).

The republisher is designed for IPNS where publishing is really expensive. For that, `WaitPub` has the right semantics.

The issue is that we're *also* using this to store the latest root on disk. In *that* case, I'd expect a call to Flush/Close (on a file) to flush all the way to disk *synchronously* (asking the user to then wait on the republisher has is pretty poor UX).

> This would entail adding a couple of checks in publish to detect if the Republisher has been closed 

The republisher doesn't currently have a concept of "closing" so I'm not sure what this would entail.

**Comment by schomatis** [comment]
> For that, `WaitPub` has the right semantics.

Could you expand on that please? My proposed solution doesn't entail generating *more* `publish` calls that we're already doing, the check in `WaitPub` would be moved to `publish`,

https://github.com/ipfs/go-mfs/blob/2c1b835ceb3a181336651f2285dc4a13b9266c32/system.go#L250-L253

which now would happen in the same lock acquisition already present (saving some contention and simplifying the code),

https://github.com/ipfs/go-mfs/blob/2c1b835ceb3a181336651f2285dc4a13b9266c32/system.go#L319-L322

> In _that_ case, I'd expect a call to Flush/Close (on a file) to flush all the way to disk _synchronously_ (asking the user to then wait on the republisher has is pretty poor UX).
> 
> >

Agreed, but that seems a responsability of the consumer of MFS who supplied the `PubFunc` in the first place, that is, if I gave you an IPNS `PubFunc` I don't call `WaitPub`/`Publish` when flushing (I let the timer run) and if I supply a save-to-disk function then I do. But that distinction doesn't seem related to calling `WaitPub` or `Publish` (which could be renamed to `PublishNow` if it makes it more clear).

> The republisher doesn't currently have a concept of "closing" so I'm not sure what this would entail.

https://github.com/ipfs/go-mfs/blob/2c1b835ceb3a181336651f2285dc4a13b9266c32/system.go#L263-L267
