### ISSUE TITLE
Avoid `closeChild` calls altogether if flush/sync is not set, remove our internal `sync` option

### ISSUE THREAD

**Issue by schomatis** [ipfs/go-mfs#39]
With the logic of the flush/sync option of the MFS API discussed and clarified in https://github.com/ipfs/go-mfs/issues/37 it seems that we either want to (when the user changes a file in the MFS) update *all* of the directories up to the root or do *nothing* (letting the final `Close` of the root to do the full update at the end to make sure nothing is lost) depending on whether the user of the API specifies the flush/sync option or not when opening a file.

At the moment, our alternative to an up-to-the-root update is not nothing but rather a kind of half-update that does just part of the job but doesn't guarantee to leave the MFS in sync at the end (we are still relying on the final `Close`). What the `closeChild` (now renamed `updateChildEntry` in https://github.com/ipfs/go-mfs/pull/36) method does when called with the `sync`/`flush` options unset is to just call `updateChild`,

https://github.com/ipfs/go-mfs/blob/2c1b835ceb3a181336651f2285dc4a13b9266c32/dir.go#L124-L127

which only updates the entry at the UnixFS layer in its internal (mutable) state,

https://github.com/ipfs/go-mfs/blob/2c1b835ceb3a181336651f2285dc4a13b9266c32/dir.go#L421-L424

that is, it doesn't regenerate the final node representing the new state with the updated entry (and hence it also doesn't add it to the DAG service nor update its parent with the new version).

That by itself it would seem to serve no purpose and it's already taken care of in `sync` (called by the root's `Close` method),

https://github.com/ipfs/go-mfs/blob/2c1b835ceb3a181336651f2285dc4a13b9266c32/dir.go#L432-L443

So the proposed solution would be to remove the `sync` option in the `closeChild` interface effectively converting it into an up-to-the-root-sync/flush mechanism that it's either called in its entirety (one `childCloser` calls its parent and its parent calls its parent's parent and so on all the way up to the root) or not at all (depending if the file was open with the `sync`/`flush` option or not).

**Comment by Stebalien** [comment]
That sounds fine but I didn't write the code so I really don't know any more than you in this case. However, make sure to update the file's inode when closing the file descriptor, even if we're not flushing.

**Comment by schomatis** [comment]
> make sure to update the file's inode when closing the file descriptor, even if we're not flushing.

Agreed, that's handled in the initial part of `flushUp` (which is always called),

https://github.com/ipfs/go-mfs/blob/e5a375ded4ae3dfbf6fca4eb1c5e606f19fdc676/fd.go#L145-L154

before starting the `updateChildEntry` chain call, the only receiver of the `fullSync` argument that this issue proposes to eliminate.
