### ISSUE TITLE
Data loss on open

### ISSUE THREAD

**Issue by Stebalien** [ipfs/go-mfs#44]
In `Open`, need to lock the file *before* getting the current node, not after. Otherwise, we could clobber previous updates.

That is, the following code needs to move *up*:

https://github.com/ipfs/go-mfs/blob/2019c381d2a6cf170ce3cc8d8b7c21a472475ea7/file.go#L88-L96

**Comment by schomatis** [comment]
Yes, that will be handled in https://github.com/ipfs/go-mfs/issues/32 (closing this to avoid duplicates, but please reopen if I'm conflating different issues).

**Comment by Stebalien** [comment]
Ah. I thought that issue looked familiar!
